//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Bootstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long ClientID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Initials { get; set; }
        public string EmployeeNumber { get; set; }
        public string IDPassport { get; set; }
        public string ContractorNo { get; set; }
        public string Street { get; set; }
        public string Block { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> EthnicalGroupID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public int EmployerID { get; set; }
        public long CreatedByID { get; set; }
        public long ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
