//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Bootstrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSite
    {
        public TestSite()
        {
            this.TestSiteWorkingSites = new HashSet<TestSiteWorkingSite>();
        }
    
        public int TestSiteID { get; set; }
        public string TestSiteName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SiteTypeID { get; set; }
        public string TestSiteAddress { get; set; }
        public string TelNo { get; set; }
        public byte[] TestSiteLogo { get; set; }
        public int EmployerID { get; set; }
        public string PolarWatchDirectoryPath { get; set; }
        public bool UseEMSSystem { get; set; }
        public bool Active { get; set; }
        public long CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedByID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual ICollection<TestSiteWorkingSite> TestSiteWorkingSites { get; set; }
    }
}
